Make CI / Build fail if npm run package not run

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -27,6 +27,11 @@ jobs:
       - name: npm run pack
         run: npm run package
 
+      - name: Check for any changed files
+        run: |
+          [[ -z $(git status --untracked-files=no --porcelain) ]] || \
+            (echo "::error title=npm run package::Files in the /dist directory should have changed. You forgot to run 'npm run package'." && exit 1)
+
   audit:
     name: Audit
     runs-on: ubuntu-latest
